; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_port = COM7 
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp8266_exception_decoder, default
upload_resetmethod = nodemcu
; تجاهل مكتبات الـ ATmega وأنت بتبني للـ ESP
lib_ignore = LCD, KEYBAD 
lib_deps = 
    adafruit/Adafruit PN532 @ ^1.3.3

[env:ATmega32]
platform = atmelavr
board = ATmega32
framework = arduino 
upload_protocol = usbasp
upload_flags = -e
board_build.f_cpu = 16000000L
; تجاهل مكتبة الـ NFC وأنت بتبني للـ ATmega
lib_ignore = NFC
build_flags = -I${PROJECT_DIR}/include