/**
 * exportStudyContent.ts
 *
 * Client-side export for all Study-with-AI result types.
 * Supports PDF (via html2pdf.js), Markdown (.md), and plain text (.txt).
 *
 * PDF strategy:
 *   Build a standalone HTML string with KaTeX pre-rendered math (via
 *   katex.renderToString) so formulas render as proper KaTeX HTML before
 *   html2canvas captures the snapshot. Raw delimiters are never left in the
 *   DOM — every $...$ and $$...$$ is converted at HTML-build time.
 *
 * Markdown/TXT strategy:
 *   Serialise the structured data directly — no DOM dependency.
 */

import katex from 'katex';

// ── Types (mirrors ClassMaterialsTab) ────────────────────────────────────────

export interface QuizItem {
  type?: string;
  difficulty?: string;
  question: string;
  options: string[];
  answer: string;
  explanation?: string;
}

export interface FlashItem {
  focus_type?: string;
  front: string;
  back: string;
  example?: string | null;
}

export interface PageItem {
  page: number;
  summary: string;
}

export type AiResultData =
  | { type: "markdown";   title: string; content: string;    action: string }
  | { type: "quiz";       title: string; items: QuizItem[];  action: string }
  | { type: "flashcards"; title: string; items: FlashItem[]; action: string }
  | { type: "pages";      title: string; pages: PageItem[];  action: string }
  | { type: "error";      title: string; content: string;    action: string };

export interface ExportMeta {
  materialName: string;
  generatedAt: Date;
  selectedOptions: Record<string, unknown>;
}

export type ExportFormat = "pdf" | "md" | "txt";

// ── Filename helpers ──────────────────────────────────────────────────────────

function slug(s: string) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
}

function buildFilename(result: AiResultData, meta: ExportMeta, fmt: ExportFormat) {
  const tool = result.action || result.type;
  const mat  = slug(meta.materialName);
  const year = meta.generatedAt.getFullYear();
  return `${tool}-${mat}-${year}.${fmt === "pdf" ? "pdf" : fmt === "md" ? "md" : "txt"}`;
}

// ── Trigger browser download ──────────────────────────────────────────────────

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a   = document.createElement("a");
  a.href     = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

// ─────────────────────────────────────────────────────────────────────────────
// Markdown serialisers
// ─────────────────────────────────────────────────────────────────────────────

function optionsTable(opts: Record<string, unknown>): string {
  const rows = Object.entries(opts)
    .filter(([, v]) => v !== undefined && v !== null && v !== "")
    .map(([k, v]) => `| ${k.replace(/_/g, " ")} | ${v} |`);
  if (!rows.length) return "";
  return `| Option | Value |\n|--------|-------|\n${rows.join("\n")}\n`;
}

function metaBlock(title: string, meta: ExportMeta): string {
  const date = meta.generatedAt.toLocaleString();
  const opts = optionsTable(meta.selectedOptions);
  return (
    `# ${title}\n\n` +
    `> **Generated by:** Study with AI — UniSystem  \n` +
    `> **Material:** ${meta.materialName}  \n` +
    `> **Date:** ${date}\n\n` +
    (opts ? `## Options\n\n${opts}\n---\n\n` : `---\n\n`)
  );
}

function markdownLetters(options: string[]): string[] {
  return options.length <= 2 ? ["A", "B"] : ["A", "B", "C", "D"];
}

function toMarkdown(result: AiResultData, meta: ExportMeta): string {
  const header = metaBlock(result.title, meta);

  if (result.type === "markdown" || result.type === "error") {
    return header + result.content + "\n";
  }

  if (result.type === "quiz") {
    const letters = ["A", "B", "C", "D"];
    const questions = result.items
      .map((q, i) => {
        const opts = q.options
          .map((o, oi) => `  - **${letters[oi]}** ${o}`)
          .join("\n");
        const badge = [q.type && `[${q.type.toUpperCase()}]`, q.difficulty && `[${q.difficulty}]`]
          .filter(Boolean).join(" ");
        const exp = q.explanation ? `\n  > **Explanation:** ${q.explanation}` : "";
        return `### Question ${i + 1} ${badge}\n\n${q.question}\n\n${opts}\n\n  **Answer:** ${q.answer}${exp}`;
      })
      .join("\n\n---\n\n");
    return header + questions + "\n";
  }

  if (result.type === "flashcards") {
    const cards = result.items
      .map((c, i) => {
        const focusBadge = c.focus_type ? ` [${c.focus_type}]` : "";
        const ex = c.example ? `\n\n  **Example:** ${c.example}` : "";
        return `### Card ${i + 1}${focusBadge}\n\n**Front:** ${c.front}\n\n**Back:** ${c.back}${ex}`;
      })
      .join("\n\n---\n\n");
    return header + cards + "\n";
  }

  if (result.type === "pages") {
    const pages = result.pages
      .map(p => `## Page ${p.page}\n\n${p.summary}`)
      .join("\n\n---\n\n");
    return header + pages + "\n";
  }

  return header;
}

function toPlainText(result: AiResultData, meta: ExportMeta): string {
  // Strip markdown syntax to get readable plain text
  const md = toMarkdown(result, meta);
  return md
    .replace(/^#{1,6}\s+/gm, "")           // headings
    .replace(/\*\*(.*?)\*\*/g, "$1")        // bold
    .replace(/\*(.*?)\*/g, "$1")            // italic
    .replace(/`([^`]+)`/g, "$1")           // inline code
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // links
    .replace(/^\s*[-*+]\s+/gm, "  • ")    // bullets
    .replace(/^\s*>\s+/gm, "    ")          // blockquotes
    .replace(/\|[^\n]+\|/g, l =>           // tables → simple
      l.replace(/\|/g, " ").replace(/\s{2,}/g, "  ").trim()
    )
    .replace(/^-{3,}$/gm, "─".repeat(40)) // rules
    .replace(/\n{3,}/g, "\n\n")
    .trim() + "\n";
}

// ─────────────────────────────────────────────────────────────────────────────
// HTML helpers for PDF body content
// ─────────────────────────────────────────────────────────────────────────────

function escHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderMathStr(latex: string, displayMode: boolean): string {
  try {
    return katex.renderToString(latex.trim(), {
      throwOnError: false,
      displayMode,
      strict: false,
    });
  } catch {
    return displayMode
      ? `<div style="font-family:monospace;overflow-x:auto">$$${escHtml(latex)}$$</div>`
      : `<code>${escHtml(latex)}</code>`;
  }
}

/** Convert basic Markdown to HTML (headings, bold, bullets, blockquotes). */
function mdToHtml(md: string): string {
  // Pre-render display math blocks ($$...$$) first — they can span multiple lines.
  const preRendered = md.replace(/\$\$([\s\S]+?)\$\$/g, (_, m) => renderMathStr(m, true));
  const lines = preRendered.split("\n");
  const out: string[] = [];
  let inUl = false;

  for (const raw of lines) {
    const line = raw;

    // headings
    const hm = line.match(/^(#{1,6})\s+(.*)/);
    if (hm) {
      if (inUl) { out.push("</ul>"); inUl = false; }
      const level = hm[1].length;
      out.push(`<h${level}>${inlineMarkdown(hm[2])}</h${level}>`);
      continue;
    }
    // hr
    if (/^---+$/.test(line.trim())) {
      if (inUl) { out.push("</ul>"); inUl = false; }
      out.push("<hr>");
      continue;
    }
    // blockquote
    if (line.startsWith("> ")) {
      if (inUl) { out.push("</ul>"); inUl = false; }
      out.push(`<blockquote>${inlineMarkdown(line.slice(2))}</blockquote>`);
      continue;
    }
    // bullet
    const bm = line.match(/^\s*[-*+]\s+(.*)/);
    if (bm) {
      if (!inUl) { out.push("<ul>"); inUl = true; }
      out.push(`<li>${inlineMarkdown(bm[1])}</li>`);
      continue;
    }
    // blank line
    if (!line.trim()) {
      if (inUl) { out.push("</ul>"); inUl = false; }
      out.push("<br>");
      continue;
    }
    // plain paragraph content
    if (inUl) { out.push("</ul>"); inUl = false; }
    out.push(`<p>${inlineMarkdown(line)}</p>`);
  }
  if (inUl) out.push("</ul>");
  return out.join("\n");
}

function inlineMarkdown(s: string): string {
  return s
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    // Pre-render math with KaTeX so html2canvas captures actual formula glyphs.
    // Display math first (longer delimiter) to avoid partial matches.
    .replace(/\$\$(.+?)\$\$/gs, (_, m) => renderMathStr(m, true))
    .replace(/\$(.+?)\$/g, (_, m) => renderMathStr(m, false));
}

// ── Per-type HTML builders ────────────────────────────────────────────────────

function quizHtml(items: QuizItem[]): string {
  const letters = ["A", "B", "C", "D"];

  return items.map((q, i) => {
    const ci = (function () {
      const up = (q.answer ?? "").trim().toUpperCase();
      const byL = letters.indexOf(up[0]);
      return byL !== -1 && byL < q.options.length ? byL : 0;
    })();

    const typeBadge  = q.type === "true_false"
      ? `<span class="badge badge-tf">T/F</span>`
      : `<span class="badge badge-mcq">MCQ</span>`;
    const diffBadge  = q.difficulty && q.difficulty !== "mixed"
      ? `<span class="badge badge-${q.difficulty}">${q.difficulty}</span>`
      : "";

    const opts = q.options.map((o, oi) => {
      const cls = oi === ci ? "correct" : "neutral";
      return `<li class="opt ${cls}">
        <span class="opt-letter">${letters[oi] ?? oi + 1}</span>
        <span>${inlineMarkdown(o)}</span>
      </li>`;
    }).join("\n");

    const exp = q.explanation
      ? `<div class="explanation"><span class="exp-label">Explanation: </span>${inlineMarkdown(q.explanation)}</div>`
      : "";

    return `<div class="q-block">
  <div class="q-header">
    <div class="q-num">${i + 1}</div>
    <div class="q-text">${inlineMarkdown(q.question)}</div>
    <div class="q-badges">${typeBadge}${diffBadge}</div>
  </div>
  <ul class="opts">${opts}</ul>
  ${exp}
</div>`;
  }).join("\n");
}

function flashcardsHtml(items: FlashItem[]): string {
  const focusClass: Record<string, string> = {
    key_terms:   "focus-key",
    definitions: "focus-def",
    formulas:    "focus-form",
  };
  const focusLabel: Record<string, string> = {
    key_terms: "Term", definitions: "Definition", formulas: "Formula", mixed: "Mixed",
  };

  const cards = items.map((c, i) => {
    const fc  = c.focus_type ? focusClass[c.focus_type] ?? "" : "";
    const fl  = c.focus_type ? focusLabel[c.focus_type] ?? c.focus_type : "";
    const badge = fl ? `<span class="focus-badge ${fc}">${fl}</span>` : "";
    const ex    = c.example
      ? `<div class="flash-example"><b>Example:</b> ${inlineMarkdown(c.example)}</div>`
      : "";
    return `<div class="flash-card">
  <div class="flash-num">Card ${i + 1}</div>
  <div class="flash-face flash-front">
    ${badge}
    <div class="flash-label">Front</div>
    <div class="flash-text">${inlineMarkdown(c.front)}</div>
  </div>
  <div class="flash-face flash-back">
    <div class="flash-label">Back</div>
    <div class="flash-text">${inlineMarkdown(c.back)}</div>
    ${ex}
  </div>
</div>`;
  }).join("\n");

  return `<div class="card-grid">${cards}</div>`;
}

function pagesHtml(pages: PageItem[]): string {
  return pages.map(p => `<div class="page-section">
  <div class="page-header">
    <div class="page-num-circle">${p.page}</div>
    <div class="page-title">Page ${p.page}</div>
  </div>
  ${mdToHtml(p.summary)}
</div>`).join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Main export entry point
// ─────────────────────────────────────────────────────────────────────────────

export async function exportStudyContent(
  result: AiResultData,
  meta: ExportMeta,
  format: ExportFormat,
  /** Live rendered DOM container — used for diagnostics only; PDF uses serialised HTML. */
  contentEl?: HTMLElement | null,
): Promise<void> {
  const filename = buildFilename(result, meta, format);

  if (format === "md") {
    const text = toMarkdown(result, meta);
    triggerDownload(new Blob([text], { type: "text/markdown;charset=utf-8" }), filename);
    return;
  }

  if (format === "txt") {
    const text = toPlainText(result, meta);
    triggerDownload(new Blob([text], { type: "text/plain;charset=utf-8" }), filename);
    return;
  }

  // ── PDF ───────────────────────────────────────────────────────────────────
  console.log("[PDF_EXPORT] Starting PDF export…");

  // ── Diagnostic: log ref state ─────────────────────────────────────────────
  if (contentEl) {
    const rect    = contentEl.getBoundingClientRect();
    const cs      = window.getComputedStyle(contentEl);
    console.log("[PDF_EXPORT] Ref diagnostics:", {
      tag:          contentEl.tagName,
      innerHTML_len: contentEl.innerHTML.length,
      clientWidth:  contentEl.clientWidth,
      clientHeight: contentEl.clientHeight,
      scrollHeight: contentEl.scrollHeight,
      rect_w:       Math.round(rect.width),
      rect_h:       Math.round(rect.height),
      children:     contentEl.children.length,
      display:      cs.display,
      opacity:      cs.opacity,
      visibility:   cs.visibility,
      overflow:     cs.overflow,
    });
  } else {
    console.warn("[PDF_EXPORT] No contentEl provided — proceeding with serialised HTML.");
  }

  // ── Build serialised content div (no <html>/<head> shell — just inner HTML) ─
  // Rationale: injecting a full <!DOCTYPE html> via innerHTML does NOT execute
  // its <script> tags and does NOT load its <link> stylesheets, so KaTeX CDN
  // never fires and the capture is blank. Instead we inject only the body
  // content wrapped in our own <style> block, reusing KaTeX CSS already loaded
  // by the app, and place it in a VISIBLE, FIXED, FULL-VIEWPORT position so
  // html2canvas can capture it without overflow-clip issues.

  const bodyContent = _buildBodyContent(result, meta);

  const exportDiv = document.createElement("div");
  exportDiv.id = "pdf-export-root";
  exportDiv.style.cssText = [
    "position:fixed",
    "top:0",
    "left:0",
    "z-index:99999",
    "width:900px",
    "background:#ffffff",
    "color:#111827",
    "overflow:visible",
    "opacity:1",
    "visibility:visible",
    "pointer-events:none",
  ].join(";");
  exportDiv.innerHTML = bodyContent;
  document.body.appendChild(exportDiv);

  console.log("[PDF_EXPORT] Export div attached:", {
    clientWidth:  exportDiv.clientWidth,
    clientHeight: exportDiv.clientHeight,
    scrollHeight: exportDiv.scrollHeight,
    innerHTML_len: exportDiv.innerHTML.length,
    children:     exportDiv.children.length,
  });

  if (exportDiv.clientHeight === 0) {
    document.body.removeChild(exportDiv);
    throw new Error("Export container has zero height — nothing to capture.");
  }

  // ── Wait: fonts → rAF paint → settle ─────────────────────────────────────
  await document.fonts.ready;
  await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
  await new Promise(r => setTimeout(r, 500));

  console.log("[PDF_EXPORT] After settle — scrollHeight:", exportDiv.scrollHeight);

  // ── Capture via html2canvas → debug PNG → jsPDF (multi-page) ────────────
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const html2canvas = ((await import("html2canvas")) as any).default;
    const { jsPDF } = await import("jspdf");

    const canvas = await html2canvas(exportDiv, {
      scale:           2,
      useCORS:         true,
      allowTaint:      true,
      logging:         true,
      backgroundColor: "#ffffff",
      windowWidth:     900,
      onclone: (clonedDoc: Document) => {
        clonedDoc.documentElement.style.cssText = "background:#ffffff!important";
        clonedDoc.body.style.cssText = "background:#ffffff!important;margin:0;padding:0";
        const root = clonedDoc.getElementById("pdf-export-root");
        console.log("[PDF_EXPORT] onclone — cloned root innerHTML length:",
          root ? root.innerHTML.length : "NOT FOUND");
      },
    });

    console.log("[PDF_EXPORT] canvas.width:", canvas.width);
    console.log("[PDF_EXPORT] canvas.height:", canvas.height);
    console.log("[PDF_EXPORT] canvas preview:", canvas.toDataURL("image/png").slice(0, 100));

    // Debug: download canvas as PNG so we can see what html2canvas captured
    const debugA = document.createElement("a");
    debugA.href = canvas.toDataURL("image/png");
    debugA.download = "debug-export-canvas.png";
    debugA.click();

    if (canvas.width === 0 || canvas.height === 0) {
      throw new Error("html2canvas returned zero-dimension canvas");
    }

    const imgData   = canvas.toDataURL("image/png");
    const pdf       = new jsPDF("p", "mm", "a4");
    const pageWidth  = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin     = 10;
    const imgWidth   = pageWidth - margin * 2;
    const imgHeight  = (canvas.height * imgWidth) / canvas.width;

    console.log("[PDF_EXPORT] imgWidth:", imgWidth, "imgHeight:", imgHeight);
    console.log("[PDF_EXPORT] pageWidth:", pageWidth, "pageHeight:", pageHeight);

    let heightLeft  = imgHeight;
    let position    = margin;
    let pagesCount  = 1;

    pdf.addImage(imgData, "PNG", margin, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - margin * 2;

    while (heightLeft > 0) {
      pdf.addPage();
      pagesCount++;
      position = heightLeft - imgHeight + margin;
      pdf.addImage(imgData, "PNG", margin, position, imgWidth, imgHeight);
      heightLeft -= pageHeight - margin * 2;
    }

    console.log("[PDF_EXPORT] pagesCount:", pagesCount, "heightLeft:", heightLeft);
    pdf.save(filename);
    console.log("[PDF_EXPORT] ✓ PDF saved successfully.");
  } catch (err) {
    console.error("[PDF_EXPORT] ✗ export threw:", err);
    throw err;
  } finally {
    document.body.removeChild(exportDiv);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Build the inner HTML content (no <html>/<head> — just styled divs).
// KaTeX CSS is already loaded globally by the app (main.tsx imports it),
// so formula rendering in katex spans works without any CDN link.
// ─────────────────────────────────────────────────────────────────────────────

function _buildBodyContent(result: AiResultData, meta: ExportMeta): string {
  const date = meta.generatedAt.toLocaleString();
  const opts = Object.entries(meta.selectedOptions)
    .filter(([, v]) => v !== undefined && v !== null && v !== "")
    .map(([k, v]) => `<span class="chip">${k.replace(/_/g, " ")}: <b>${v}</b></span>`)
    .join(" ");

  let body: string;
  if (result.type === "quiz") {
    body = quizHtml(result.items);
  } else if (result.type === "flashcards") {
    body = flashcardsHtml(result.items);
  } else if (result.type === "pages") {
    body = pagesHtml(result.pages);
  } else {
    body = mdToHtml((result as { content: string }).content);
  }

  return `
<style>
  #pdf-export-root * { box-sizing: border-box; }
  #pdf-export-root {
    font-family: "Segoe UI", system-ui, sans-serif;
    font-size: 12pt;
    color: #1e293b;
    background: #ffffff;
    padding: 0;
  }
  .pdf-cover {
    padding: 36px 48px 28px;
    border-bottom: 3px solid #0891b2;
    background: linear-gradient(135deg, #f0f9ff 0%, #fff 60%);
  }
  .pdf-brand  { font-size: 9pt; font-weight: 700; color: #0891b2; letter-spacing: .1em; text-transform: uppercase; margin-bottom: 8px; }
  .pdf-title  { font-size: 22pt; font-weight: 800; color: #0f172a; line-height: 1.2; }
  .pdf-sub    { font-size: 10pt; color: #64748b; margin-top: 4px; }
  .pdf-date   { font-size: 8.5pt; color: #94a3b8; margin-top: 6px; }
  .pdf-chips  { margin-top: 10px; display: flex; flex-wrap: wrap; gap: 5px; }
  .chip { background:#e0f2fe; color:#0369a1; border-radius:99px; padding:2px 10px; font-size:8pt; border:1px solid #bae6fd; }
  .pdf-body   { padding: 28px 48px 48px; }
  h1 { font-size:16pt; color:#0f172a; margin:24px 0 10px; padding-bottom:6px; border-bottom:2px solid #e2e8f0; }
  h2 { font-size:13pt; color:#1e293b; margin:20px 0 8px; }
  h3 { font-size:11pt; color:#334155; margin:14px 0 6px; }
  p  { line-height:1.7; margin:6px 0; }
  ul { padding-left:20px; margin:6px 0; }
  li { margin:3px 0; line-height:1.6; }
  blockquote { border-left:3px solid #0891b2; margin:8px 0; padding:4px 12px; color:#475569; background:#f8fafc; border-radius:0 4px 4px 0; }
  code { background:#f1f5f9; padding:1px 5px; border-radius:3px; font-size:9.5pt; font-family:monospace; color:#1d4ed8; }
  hr   { border:none; border-top:1px solid #e2e8f0; margin:18px 0; }

  /* Quiz */
  .q-block  { margin:18px 0; padding:16px 18px; border:1px solid #e2e8f0; border-radius:10px; background:#f8fafc; page-break-inside:avoid; }
  .q-header { display:flex; align-items:flex-start; gap:8px; margin-bottom:10px; }
  .q-num    { min-width:28px; height:28px; border-radius:50%; background:#0891b2; color:#fff; font-weight:700; font-size:10pt; display:flex; align-items:center; justify-content:center; flex-shrink:0; }
  .q-text   { font-weight:600; font-size:11pt; flex:1; }
  .q-badges { display:flex; gap:4px; flex-shrink:0; }
  .badge    { padding:1px 8px; border-radius:99px; font-size:7.5pt; font-weight:700; border:1px solid; }
  .badge-mcq    { background:#dbeafe; color:#1d4ed8; border-color:#bfdbfe; }
  .badge-tf     { background:#ede9fe; color:#6d28d9; border-color:#ddd6fe; }
  .badge-easy   { background:#d1fae5; color:#065f46; border-color:#a7f3d0; }
  .badge-medium { background:#fef3c7; color:#92400e; border-color:#fde68a; }
  .badge-hard   { background:#fee2e2; color:#991b1b; border-color:#fecaca; }
  .opts     { list-style:none; padding:0; display:flex; flex-direction:column; gap:5px; }
  .opt      { display:flex; align-items:flex-start; gap:8px; padding:6px 10px; border-radius:7px; font-size:10pt; }
  .opt.correct { background:#d1fae5; color:#065f46; }
  .opt.neutral { background:#fff; border:1px solid #e2e8f0; color:#475569; }
  .opt-letter { width:22px; height:22px; border-radius:50%; border:1.5px solid currentColor; display:flex; align-items:center; justify-content:center; font-size:9pt; font-weight:700; flex-shrink:0; }
  .explanation { margin-top:10px; padding:8px 12px; border-radius:7px; background:#f1f5f9; border-left:3px solid #0891b2; font-size:9.5pt; color:#475569; }
  .exp-label   { font-weight:700; color:#0369a1; }

  /* Flashcards */
  .card-grid  { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
  .flash-card { border:1.5px solid #e2e8f0; border-radius:10px; overflow:hidden; page-break-inside:avoid; }
  .flash-num  { font-size:8pt; color:#94a3b8; padding:6px 12px 0; }
  .flash-face { padding:12px; }
  .flash-front{ background:#f8fafc; border-bottom:1.5px solid #e2e8f0; }
  .flash-back { background:#fff; }
  .flash-label{ font-size:7.5pt; font-weight:700; letter-spacing:.1em; text-transform:uppercase; color:#0891b2; margin-bottom:4px; }
  .flash-text { font-size:10pt; line-height:1.5; color:#1e293b; }
  .flash-example { margin-top:8px; padding:6px 10px; background:#fffbeb; border-left:2px solid #f59e0b; border-radius:4px; font-size:9pt; color:#92400e; }
  .focus-badge{ display:inline-block; padding:1px 8px; border-radius:99px; font-size:7pt; font-weight:700; margin-bottom:6px; }
  .focus-key  { background:#cffafe; color:#0e7490; border:1px solid #a5f3fc; }
  .focus-def  { background:#e0e7ff; color:#3730a3; border:1px solid #c7d2fe; }
  .focus-form { background:#fce7f3; color:#9d174d; border:1px solid #fbcfe8; }

  /* Page-by-page */
  .page-section { margin:18px 0; padding:14px 18px; border:1px solid #e2e8f0; border-radius:10px; page-break-inside:avoid; }
  .page-header  { display:flex; align-items:center; gap:10px; margin-bottom:10px; }
  .page-num-circle { width:30px; height:30px; border-radius:50%; background:#0891b2; color:#fff; font-weight:800; font-size:10pt; display:flex; align-items:center; justify-content:center; flex-shrink:0; }
  .page-title { font-weight:700; font-size:11pt; color:#1e293b; }
</style>
<div class="pdf-cover">
  <div class="pdf-brand">UniSystem · Study with AI</div>
  <div class="pdf-title">${escHtml(result.title)}</div>
  <div class="pdf-sub">${escHtml(meta.materialName)}</div>
  <div class="pdf-date">Generated on ${date}</div>
  ${opts ? `<div class="pdf-chips">${opts}</div>` : ""}
</div>
<div class="pdf-body">
${body}
</div>`;
}
